# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

sudo: false

cache:
  packages: true

env:
 global:
   - CRAN: http://cran.rstudio.com

r_packages:
  - covr
  - dplyr
  - htmlwidgets
  - testthat

warnings_are_errors: false

r_build_args: "--no-build-vignettes"

after_success:
  - Rscript -e 'covr::codecov()'
